name: asana-exporter
version: '1.0'
summary: Extract Asana data and import into Jira
description:
  Exports data such as projects from Asana and stores them in a format that is easy to import into other tools.
confinement: strict
grade: stable
base: core20

apps:
  asana-exporter:
    command: bin/asana-exporter
    plugs:
      - home
      - network
parts:
  asana-exporter:
    plugin: python
    source: .
    requirements:
      - requirements.txt

