name: asana-to-jira 
version: '1.0'
summary: Extract Asana data and import into Jira
description:
  Tool to extract data such as projects from Asana and import them into Jira.
confinement: strict
grade: stable
base: core20

apps:
  asana-to-jira:
    command: bin/asana-to-jira
    plugs:
      - home
      - network
parts:
  asana-to-jira:
    plugin: python
    source: .
    requirements:
      - requirements.txt

