name: asana-exporter
version: '1.0'
summary: Export data from Asana
description: |
    Exports data such as projects from Asana and stores them in a format that is easy to import into other tools.

    Project maintained at https://github.com/dosaboy/asana-to-jira
confinement: strict
grade: stable
base: core20

apps:
  asana-exporter:
    command: bin/asana-exporter
    plugs:
      - home
      - network
parts:
  asana-exporter:
    plugin: python
    source: .
    requirements:
      - requirements.txt

